config/routes.rb
Ntstwitter::Application.routes.draw do
  root to: 'tweets#index'

  resources :tweets

  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  Twitter.configure do |config|
    config.consumer_key       = 'YOUR CONSUMER KEY'
    config.consumer_secret    = 'YOUR CONSUMER SECRET'
    config.oauth_token        = 'YOUR OAUTH TOKEN'
    config.oauth_token_secret = 'YOUR OAUTH TOKEN SECRET'
  end

  def self.search(keyword, options = {})
    Twitter.search(keyword || '#rubyjp').results
  end

  def self.update(text)
    Twitter.update(text)
  end

  def self.status(status_id)
    Twitter.status(status_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  def index
    @search_keyword = params[:tweet][:q] if params[:tweet]
    @search_keyword ||= '#rubyjp'
    @tweets = Tweet.search(@search_keyword)
  end

  # GET /tweets/1
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)

    if Tweet.update("#{@tweet.content} by #{@tweet.from_user_name} at #{Time.now.strftime('%Y/%m/%d %H:%M:%S')} via NtsTweet")
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.status(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tweet_params
      params.require(:tweet).permit(:id, :content, :from_user_id, :from_user_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ntstwitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, html: {class: 'form-horizontal well'}) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :content, '内容', class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, cols: 40 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :from_user_name, 'ユーザー名', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :from_user_name %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Tweet', class: 'btn' %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>「<%= @search_keyword %>」の検索結果</h1>

<div id="search_form_box">
  <%= form_tag tweets_path, method: :get, class: 'form-search' do %>
    <%= text_field :tweet, :q, class: 'input-medium search-query', placeholder: 'Search', value: @search_keyword %>
    <%= submit_tag '検索', class: 'btn' %>
    <%= link_to '新規つぶやき', new_tweet_path, class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="well">
<table class="table table-striped">
  <thead>
    <tr>
      <th>ユーザー</th>
      <th>つぶやき</th>
      <th>tweetを見る</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td>
          <a href="<%= "https://twitter.com/#{tweet.user.screen_name}" %>" target="_blank">
            <%= image_tag tweet.user.profile_image_url, alt: tweet.user.name %>
          </a>
        </td>
        <td><%= tweet.text %></td>
        <td><%= link_to "@#{tweet.user.screen_name}", "https://twitter.com/#{tweet.user.screen_name}/status/#{tweet.id}" %></td>
        <td><%= link_to '詳細', tweet_path(tweet.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/tweets/new.html.erb
<h1>つぶやく</h1>

<%= render 'form' %>

<%= link_to '戻る', tweets_path, class: 'btn' %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tweet.id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>From user:</strong>
  <%= @tweet.user.name %>
</p>

<p>
  <strong>From user name:</strong>
  @<%= @tweet.user.screen_name %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>